// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _6_MoviesEntities.Contexts;

#nullable disable

namespace _6_MoviesEntities.Migrations.MoviesNpgSql
{
    [DbContext(typeof(MoviesNpgSqlContext))]
    [Migration("20241019182113_npgsqlinit2")]
    partial class npgsqlinit2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryMovie", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer");

                    b.Property<int>("MoviesId")
                        .HasColumnType("integer");

                    b.HasKey("CategoriesId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("CategoryMovie");
                });

            modelBuilder.Entity("_6_MoviesEntities.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Drama",
                            CreateDate = new DateTime(2024, 10, 19, 18, 21, 13, 476, DateTimeKind.Utc).AddTicks(5680),
                            Description = "Drama"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Sci-Fi",
                            CreateDate = new DateTime(2024, 10, 19, 18, 21, 13, 476, DateTimeKind.Utc).AddTicks(5680),
                            Description = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Comedy",
                            CreateDate = new DateTime(2024, 10, 19, 18, 21, 13, 476, DateTimeKind.Utc).AddTicks(5690),
                            Description = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Adventure",
                            CreateDate = new DateTime(2024, 10, 19, 18, 21, 13, 476, DateTimeKind.Utc).AddTicks(5690),
                            Description = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Crime",
                            CreateDate = new DateTime(2024, 10, 19, 18, 21, 13, 476, DateTimeKind.Utc).AddTicks(5690),
                            Description = "Crime"
                        });
                });

            modelBuilder.Entity("_6_MoviesEntities.Entities.Concrete.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<short?>("Duration")
                        .HasColumnType("smallint");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("_6_MoviesEntities.Entities.Concrete.Saloon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Kapasite")
                        .HasColumnType("smallint");

                    b.Property<string>("SalonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Salons");
                });

            modelBuilder.Entity("_6_MoviesEntities.Entities.Concrete.Seans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("SeansSaati")
                        .HasMaxLength(50)
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("Seans");
                });

            modelBuilder.Entity("_6_MoviesEntities.Entities.Concrete.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("SaloonId")
                        .HasColumnType("integer");

                    b.Property<int>("SeansId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("SeansId");

                    b.HasIndex("WeekId");

                    b.HasIndex("SaloonId", "SeansId", "WeekId")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("_6_MoviesEntities.Entities.Concrete.Week", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("WeekName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Weeks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 10, 19, 21, 21, 13, 480, DateTimeKind.Local).AddTicks(4980),
                            EndDate = new DateOnly(2025, 8, 14),
                            StartDate = new DateOnly(2023, 8, 14),
                            WeekName = "W32"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 10, 19, 21, 21, 13, 480, DateTimeKind.Local).AddTicks(4990),
                            EndDate = new DateOnly(2025, 8, 14),
                            StartDate = new DateOnly(2023, 8, 14),
                            WeekName = "W33"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 10, 19, 21, 21, 13, 480, DateTimeKind.Local).AddTicks(5000),
                            EndDate = new DateOnly(2025, 8, 14),
                            StartDate = new DateOnly(2023, 8, 14),
                            WeekName = "W34"
                        });
                });

            modelBuilder.Entity("CategoryMovie", b =>
                {
                    b.HasOne("_6_MoviesEntities.Entities.Concrete.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_6_MoviesEntities.Entities.Concrete.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_6_MoviesEntities.Entities.Concrete.Session", b =>
                {
                    b.HasOne("_6_MoviesEntities.Entities.Concrete.Movie", "Movie")
                        .WithMany("Sessions")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_6_MoviesEntities.Entities.Concrete.Saloon", "Saloon")
                        .WithMany("Sessions")
                        .HasForeignKey("SaloonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_6_MoviesEntities.Entities.Concrete.Seans", "Seans")
                        .WithMany("Sessions")
                        .HasForeignKey("SeansId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_6_MoviesEntities.Entities.Concrete.Week", "Week")
                        .WithMany("Sessions")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Saloon");

                    b.Navigation("Seans");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("_6_MoviesEntities.Entities.Concrete.Movie", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("_6_MoviesEntities.Entities.Concrete.Saloon", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("_6_MoviesEntities.Entities.Concrete.Seans", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("_6_MoviesEntities.Entities.Concrete.Week", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
