// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _8_TablePerHierarchy;

#nullable disable

namespace _8_TablePerHierarchy.Migrations
{
    [DbContext(typeof(Program.PgSqlContext))]
    partial class PgSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_8_TablePerHierarchy.Program+Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Araclar");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Arac");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("_8_TablePerHierarchy.Program+Motorsiklet", b =>
                {
                    b.HasBaseType("_8_TablePerHierarchy.Program+Arac");

                    b.Property<byte>("MotorsikletTipi")
                        .HasColumnType("smallint");

                    b.HasDiscriminator().HasValue("Motorsiklet");
                });

            modelBuilder.Entity("_8_TablePerHierarchy.Program+Otobus", b =>
                {
                    b.HasBaseType("_8_TablePerHierarchy.Program+Arac");

                    b.Property<byte>("KoltukSayisi")
                        .HasColumnType("smallint");

                    b.HasDiscriminator().HasValue("Otobus");
                });

            modelBuilder.Entity("_8_TablePerHierarchy.Program+Otomobil", b =>
                {
                    b.HasBaseType("_8_TablePerHierarchy.Program+Arac");

                    b.Property<byte>("KasaTipi")
                        .HasColumnType("smallint");

                    b.HasDiscriminator().HasValue("Otomobil");
                });
#pragma warning restore 612, 618
        }
    }
}
